#!/bin/bash

# Check if at least 3 parameters are passed
if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Disable strict host key checking for ssh
SSH_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file using scp
scp -i "$PATH_TO_SSH_KEY" $SSH_OPTIONS "$PATH_TO_FILE" "$USERNAME"@"$IP":~/.

if [ $? -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$IP:~/".
else
    echo "File transfer failed."
fi
