#!/usr/bin/env bash
# Installs HAProxy version 2.4

#package for managing repos
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get update

#install HAProxy version 2.4
apt-get install -y haproxy=2.4.\*

#enable HAProxy to start at boot
echo "ENABLED=1" >> /etc/default/haproxy

#backup existing haproxy.cfg file
mv /etc/haproxy/haproxy.cfg{,.original}

#create empty haproxy.cfg
touch /etc/haproxy/haproxy.cfg

#configuration block
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 20205-web-01 44.192.38.3 check
    server 20205-web-02 3.239.82.120 check
" >> /etc/haproxy/haproxy.cfg

#Start HAProxy
service haproxy start
