#!/usr/bin/env bash
#display numbers from 1 to 100
#fizzbuzz game
i=1
while (( i <= 100 ))
do
	if (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	elif(( i % 5 == 0 && i % 3 == 0 ))
	then
		echo "FizzBuzz"
	else
	echo "$i"
       fi
	((i++))
done

