#!/usr/bin/env bash
IFS=':'
while read -r uname passwd uid groupid desc home shell; do
	echo "The user $uname is part of the $groupid gang, lives in $home and rides $shell. $uid's place is protected by passcode $passwd, more info about the user here: $desc"
done </etc/passwd
